### ISSUE TITLE
Injected SyntaxError

### ISSUE THREAD

**Issue by jayvdb** [adsharma/py2many#272]
When running pyrs on https://github.com/swift-nav/piksi_tools/blob/55d5d4e/piksi_tools/console/utils.py#L678 , py2many does this transform:
```diff
-    if code_is_glo(code):
+    if code_is_glo(code: int):
```

which causes

```py
Traceback (most recent call last):
  File "/Users/john.vandenberg/python/py2many/py2many.py", line 16, in <module>
    main()
  File "/Users/john.vandenberg/python/py2many/py2many/cli.py", line 414, in main
    rv = _process_once(settings, source, outdir, env=env)
  File "/Users/john.vandenberg/python/py2many/py2many/cli.py", line 286, in _process_once
    transpile(
  File "/Users/john.vandenberg/python/py2many/py2many/cli.py", line 79, in transpile
    tree = ast.parse(source)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 657
    if code_is_glo(code: int):
                       ^
SyntaxError: invalid syntax
```

**Comment by jayvdb** [comment]
Ugh, my bad, this was caused by my pre-processor.
